In [1]:
import pandas as pd

In [15]:
df2 = pd.read_excel('studmepsinsurance-2.xls')

FileNotFoundError: [Errno 2] No such file or directory: 'studmepsinsurance-2.xls'

In [6]:
df.head()

   Unnamed: 0  year  age sex  consultations  population  perCapita
0           5  2006    1   m        78700.0     29535.0   2.664635
1           8  2006    2   m        57272.0     29504.0   1.941161
2          11  2006    3   m        47374.0     28894.0   1.639579
3          14  2006    4   m        39366.0     29576.0   1.331012
4          17  2006    5   m        36272.0     30953.0   1.171841

In [4]:
df

     Unnamed: 0  year  age sex  consultations  population  perCapita
0             5  2006    1   m        78700.0     29535.0   2.664635
1             8  2006    2   m        57272.0     29504.0   1.941161
2            11  2006    3   m        47374.0     28894.0   1.639579
3            14  2006    4   m        39366.0     29576.0   1.331012
4            17  2006    5   m        36272.0     30953.0   1.171841
5            20  2006    6   m        32231.0     31138.0   1.035102
6            23  2006    7   m        28698.0     30705.0   0.934636
7            26  2006    8   m        26721.0     31732.0   0.842084
8            29  2006    9   m        27258.0     32495.0   0.838837
9            32  2006   10   m        27171.0     32204.0   0.843715
10           35  2006   11   m        26582.0     31994.0   0.830843
11           38  2006   12   m        22541.0     31649.0   0.712218
12           41  2006   13   m        23847.0     32497.0   0.733822
13           44  2006   14   m        24971.0     32743.0   0.762636
14           47  2006   15   m        25482.0     32617.0   0.781249
15           50  2006   16   m        25713.0     31807.0   0.808407
16           53  2006   17   m        26038.0     30961.0   0.840994
17           56  2006   18   m        29513.0     29205.0   1.010546
18           59  2006   19   m        30685.0     28844.0   1.063826
19           62  2006   20   m        31315.0     28111.0   1.113977
20           65  2006   21   m        31548.0     27636.0   1.141554
21           68  2006   22   m        32504.0     27785.0   1.169840
22           71  2006   23   m        33758.0     28328.0   1.191683
23           74  2006   24   m        34800.0     27728.0   1.255049
24           77  2006   25   m        35908.0     28564.0   1.257107
25           80  2006   26   m        37324.0     28661.0   1.302257
26           83  2006   27   m        38933.0     29052.0   1.340114
27           86  2006   28   m        38784.0     28571.0   1.357460
28           89  2006   29   m        40666.0     29942.0   1.358159
29           92  2006   30   m        43779.0     31353.0   1.396326
..          ...   ...  ...  ..            ...         ...        ...
682        2488  2013   60   m        83988.0     29623.0   2.835229
683        2490  2013   61   m        82226.0     28378.0   2.897526
684        2492  2013   62   m        82105.0     28610.0   2.869801
685        2494  2013   63   m        83553.0     28569.0   2.924604
686        2496  2013   64   m        86248.0     28832.0   2.991398
687        2498  2013   65   m        88693.0     28886.0   3.070449
688        2501  2013   66   m        91661.0     29757.0   3.080317
689        2504  2013   67   m        89455.0     26071.0   3.431207
690        2506  2013   68   m        85178.0     24842.0   3.428790
691        2508  2013   69   m        82328.0     21617.0   3.808484
692        2510  2013   70   m        72626.0     19383.0   3.746892
693        2512  2013   71   m        66867.0     16450.0   4.064863
694        2515  2013   72   m        62077.0     16807.0   3.693521
695        2517  2013   73   m        64668.0     15730.0   4.111125
696        2519  2013   74   m        63738.0     14702.0   4.335329
697        2521  2013   75   m        62165.0     13455.0   4.620216
698        2523  2013   76   m        59239.0     12560.0   4.716481
699        2525  2013   77   m        55597.0     11355.0   4.896257
700        2527  2013   78   m        52426.0     10856.0   4.829219
701        2530  2013   79   m        51787.0     10359.0   4.999228
702        2532  2013   80   m        51939.0     10373.0   5.007134
703        2534  2013   81   m        50965.0      9540.0   5.342243
704        2536  2013   82   m        47212.0      9039.0   5.223144
705        2538  2013   83   m        43592.0      8039.0   5.422565
706        2541  2013   84   m        38012.0      7322.0   5.191478
707        2544  2013   85   m        33794.0      6376.0   5.300188
708        2547  2013   86   m        29800.0      5924.0   5.030385
709        2549  2013   87   m        26950.0      5182.0   5.200695
710        2551  2013   88   m        22423.0      4355.0   5.148794
711        2553  2013   89   m        17517.0      3660.0   4.786066

[712 rows x 7 columns]